local gameConfig = {
	[1] = {
		id = 1,
		scene = "BaccaratScene",
		icon = "public/icon_4.png",
		name = "public/game_type_2.png",
		corner = "public/game_xian.png",
		mode = 1,
		show = true,
	},
	[2] = {
		id = 2,
		scene = "BaccaratScene",
		icon = "public/icon_4.png",
		name = "public/game_type_2.png",
		corner = "public/game_zhuang.png",
		mode = 2,
		show = true,
	},
	[3] = {
		id = 3,
		scene = "DdzScene",
		icon = "public/icon_0.png",
		name = "public/game_type_5.png",
		corner = nil,
		mode = 1,
		show = false,
	},
	[4] = {
		id = 4,
		scene = "DdzScene",
		icon = "public/icon_0.png",
		name = "public/game_type_5.png",
		corner = nil,
		mode = 2,
		show = false,
	},
	[5] = {
		id = 5,
		scene = "DdzScene",
		icon = "public/icon_0.png",
		name = "public/game_type_5.png",
		corner = nil,
		mode = 3,
		show = false,
	},
	[6] = {
		id = 6,
		scene = "CChessScene",
		icon = "public/icon_0.png",
		name = "public/game_type_5.png",
		corner = nil,
		mode = 1,
		show = false,
	},
	[7] = {
		id = 7,
		scene = "CChessScene",
		icon = "public/icon_0.png",
		name = "public/game_type_5.png",
		corner = nil,
		mode = 2,
		show = false,
	},
	[8] = {
		id = 8,
		scene = "CChessScene",
		icon = "public/icon_0.png",
		name = "public/game_type_5.png",
		corner = nil,
		mode = 3,
		show = false,
	},
	[9] = {
		id = 9,
		scene = "WzqScene",
		icon = "public/icon_0.png",
		name = "public/game_type_5.png",
		corner = nil,
		mode = 1,
		show = false,
	},
}

return gameConfig